#!/bin/bash

#SBATCH -J ecsg
#SBATCH -o test.o%j
#SBATCH -e test.e%j
#SBATCH -p normal
#SBATCH -t 00:59:00
#SBATCH --mail-user=mz10@rice.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

#SBATCH -n 1
#SBATCH -N 1
        
cd /work/02049/mz10/ecsg/tests/test1-cmp-eci-ii/eci &&
FIGDIR="$RSFFIGS/tests/test1-cmp-eci-ii/eci" &&
TESTDIR="/work/02049/mz10/ecsg/tests/test1-cmp-eci-ii" &&
# test1
cp $TESTDIR/par1.py $TESTDIR/pareci.py &&
scons -c &&
scons lock &&
scons rec_out.hh &&
scons rec_trace.hh &&
cp rec_out.hh $FIGDIR/rec_eci_test1.hh &&
cp rec_trace.hh $FIGDIR/geo_eci_test1.hh &&

# test2
cp $TESTDIR/par2.py $TESTDIR/pareci.py &&
scons -c &&
scons lock &&
scons rec_out.hh &&
scons rec_trace.hh &&
cp rec_out.hh $FIGDIR/rec_eci_test2.hh &&
cp rec_trace.hh $FIGDIR/geo_eci_test2.hh &&

# test2
cp $TESTDIR/par3.py $TESTDIR/pareci.py &&
scons -c &&
scons lock &&
scons rec_out.hh &&
scons rec_trace.hh &&
cp rec_out.hh $FIGDIR/rec_eci_test3.hh &&
cp rec_trace.hh $FIGDIR/geo_eci_test3.hh &&

# clean up
cd $FIGDIR &&
rm movie_cg.vpl movie_vx* ricker* &&
vpconvert *.vpl format=pdf &&
rm *.vpl &&
rm /work/02049/mz10/ecsg/tests/test1-cmp-eci-ii/pareci*
